# Generated by Django 5.1.4 on 2026-06-01 20:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Estadio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Estadio',
                'verbose_name_plural': 'Estadios',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Fase',
            fields=[
                ('id_fase', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Fase',
                'verbose_name_plural': 'Fases',
                'ordering': ['id_fase'],
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('grupo', models.SmallIntegerField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='flags/')),
                ('es_campeon', models.BooleanField(default=False)),
                ('emoji', models.CharField(blank=True, max_length=10)),
            ],
            options={
                'verbose_name': 'País',
                'verbose_name_plural': 'Países',
                'ordering': ['grupo', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=120)),
                ('edad', models.SmallIntegerField()),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jugadores', to='polla.pais')),
            ],
            options={
                'verbose_name': 'Jugador',
                'verbose_name_plural': 'Jugadores',
                'ordering': ['pais', 'nombre_completo'],
            },
        ),
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(blank=True, null=True)),
                ('goles_local', models.SmallIntegerField(blank=True, null=True)),
                ('goles_visitante', models.SmallIntegerField(blank=True, null=True)),
                ('hubo_penales', models.BooleanField(default=False)),
                ('penales_local', models.SmallIntegerField(blank=True, null=True)),
                ('penales_visitante', models.SmallIntegerField(blank=True, null=True)),
                ('jugado', models.BooleanField(default=False)),
                ('estadio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='polla.estadio')),
                ('fase', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='partidos', to='polla.fase')),
                ('pais_local', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='partidos_local', to='polla.pais')),
                ('pais_visitante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='partidos_visitante', to='polla.pais')),
            ],
            options={
                'verbose_name': 'Partido',
                'verbose_name_plural': 'Partidos',
                'ordering': ['fecha', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntos_campeon', models.SmallIntegerField(default=0)),
                ('puntos_goleador', models.SmallIntegerField(default=0)),
                ('campeon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pronosticantes_campeon', to='polla.pais')),
                ('goleador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pronosticantes_goleador', to='polla.jugador')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfiles',
            },
        ),
        migrations.CreateModel(
            name='GolPartido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.SmallIntegerField(default=1)),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goles_anotados', to='polla.jugador')),
                ('partido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goles', to='polla.partido')),
            ],
            options={
                'verbose_name': 'Gol en partido',
                'verbose_name_plural': 'Goles en partidos',
                'unique_together': {('jugador', 'partido')},
            },
        ),
        migrations.CreateModel(
            name='Pronostico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goles_local', models.SmallIntegerField()),
                ('goles_visitante', models.SmallIntegerField()),
                ('predice_penales', models.BooleanField(default=False)),
                ('puntos', models.SmallIntegerField(default=0)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('partido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pronosticos', to='polla.partido')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pronosticos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pronóstico',
                'verbose_name_plural': 'Pronósticos',
                'unique_together': {('usuario', 'partido')},
            },
        ),
    ]
