# Generated by Django 5.1.4 on 2026-06-01 22:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polla', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilusuario',
            name='goleador',
        ),
        migrations.RemoveField(
            model_name='perfilusuario',
            name='puntos_goleador',
        ),
        migrations.CreateModel(
            name='SeleccionJugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntos_acumulados', models.SmallIntegerField(default=0)),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selecciones', to='polla.jugador')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jugadores_seleccionados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Jugador seleccionado',
                'verbose_name_plural': 'Jugadores seleccionados',
                'unique_together': {('usuario', 'jugador')},
            },
        ),
    ]
