# Generated by Django 5.1.4 on 2026-06-01 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polla', '0002_seleccion_jugador_fix_scoring'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='telefono',
            field=models.CharField(blank=True, help_text='Formato internacional: 591XXXXXXXX', max_length=20),
        ),
    ]
