# Generated by Django 5.1.4 on 2026-06-01 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polla', '0003_add_telefono_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='partido',
            name='fd_match_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='football-data.org ID'),
        ),
    ]
