# Generated by Django 5.1.4 on 2026-06-01 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polla', '0004_add_fd_match_id_lockout'),
    ]

    operations = [
        migrations.CreateModel(
            name='TorneoConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Mi Polla', max_length=120)),
                ('temporada', models.CharField(default='2026', help_text='Ej: 2026, Copa América 2024', max_length=30)),
                ('logo', models.ImageField(blank=True, help_text='Logo del torneo (recomendado: fondo transparente, PNG)', null=True, upload_to='torneo/')),
                ('color_primario', models.CharField(default='#6366f1', help_text='Color principal en hex, ej: #6366f1', max_length=7)),
                ('color_secundario', models.CharField(default='#10b981', help_text='Color secundario en hex', max_length=7)),
            ],
            options={
                'verbose_name': 'Configuración del torneo',
                'verbose_name_plural': 'Configuración del torneo',
            },
        ),
    ]
