# Generated by Django 5.1.4 on 2026-06-02 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polla', '0005_torneo_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='torneoconfig',
            name='cuota',
            field=models.DecimalField(decimal_places=2, default=100.0, help_text='Cuota de inscripción por participante en Bs.', max_digits=8),
        ),
        migrations.AddField(
            model_name='torneoconfig',
            name='pozo_activo',
            field=models.BooleanField(default=True, help_text='Mostrar la página El Gran Pozo'),
        ),
    ]
