# Generated by Django 5.1.4 on 2026-06-22 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polla', '0008_inscripciones_abiertas'),
    ]

    operations = [
        migrations.AddField(
            model_name='partido',
            name='correo_enviado',
            field=models.BooleanField(default=False, help_text='Si ya se envió el correo de transparencia con los pronósticos al cierre de este partido'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='recibir_correos',
            field=models.BooleanField(default=False, help_text='Recibir por correo los pronósticos de todos al cierre de cada partido (transparencia)'),
        ),
        migrations.AddField(
            model_name='torneoconfig',
            name='correo_apertura_enviado',
            field=models.BooleanField(default=False, help_text='Si ya se envió el correo especial de apertura (jugadores, campeones y 1er partido)'),
        ),
    ]
